### ISSUE TITLE
Multiple value Sensor Deployment

### ISSUE THREAD

**Issue by mvishnuprathap** [LSIR/gsn#73]
How can we implement a multiple value sensing sensor in GSN other than the example ones given in the GSN. I would like to deploy a sensor that measures pressure as well as temperature.

**Comment by ebiiii** [comment]
It depends if the measurements are synchronized or not. If you always measure the pressure at the same time as temperature, you can simply have two fields in your output stream (when defining the virtual sensor in the xml file). Otherwise, you may want to have separated virtual sensors and store the temperature and pressure separately.
